version: '2'
services:
  db:
    extends:
      file: mysql/base.yml
      service: db
  phpmyadmin:
    extends:
      file: phpmyadmin/base.yml
      service: phpmyadmin
  php:
    extends:
      file: php7/base.yml
      service: php
  web:
    extends:
      file: nginx/base.yml
      service: web
  redis:
    extends:
      file: redis/base.yml
      service: redis
