doctrine_migrations:
    dir_name: '%kernel.project_dir%/src/DoctrineMigrations'
    # namespace is arbitrary but should be different from App\Migrations
    # as migrations classes should NOT be autoloaded
    namespace: App\DoctrineMigrations
    table_name: 'migration_versions'
    column_name: 'version'
    column_length: 14
    executed_at_column_name: 'executed_at'
    name: 'Application Migrations'
    # available in version >= 1.2. Possible values: "BY_YEAR", "BY_YEAR_AND_MONTH", false
    organize_migrations: false
    # available in version >= 1.3. Path to your custom migrations template
    custom_template: ~
    all_or_nothing: false

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8

        # With Symfony 3.3, remove the `resolve:` prefix
        url: '%env(DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App/SocialManagement/User/Domain:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/SocialManagement/User/Domain'
                prefix: 'App\SocialManagement\User\Domain'
                alias: App/SocialManagement/User/Domain
            App/SocialManagement/Group/Domain:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/SocialManagement/Group/Domain'
                prefix: 'App\SocialManagement\Group\Domain'
                alias: App/SocialManagement/Group/Domain
            App/SocialManagement/UserGroup/Domain:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/SocialManagement/UserGroup/Domain'
                prefix: 'App\SocialManagement\UserGroup\Domain'
                alias: App/SocialManagement/UserGroup/Domain
            App/SocialManagement/Meeting/Domain:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/SocialManagement/Meeting/Domain'
                prefix: 'App\SocialManagement\Meeting\Domain'
                alias: App/SocialManagement/Meeting/Domain
            App/SocialManagement/UserMeeting/Domain:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/SocialManagement/UserMeeting/Domain'
                prefix: 'App\SocialManagement\UserMeeting\Domain'
                alias: App/SocialManagement/UserMeeting/Domain
