monolog:

  handlers:
    main:
      type:      stream
      level:     warning
      formatter: app.infrastructure.monolog.formatter.logstash
      channels:  ['!api']
    api_request:
      type:      stream
      path:      "%kernel.logs_dir%/%kernel.environment%.api.requests.log"
      level:     warning
      formatter: app.infrastructure.monolog.formatter.logstash
      channels:  ['api']
    events:
      type:      stream
      path:      "%kernel.logs_dir%/%kernel.environment%.events.log"
      level:     error
      formatter: app.infrastructure.monolog.formatter.logstash
      channels:  ['events']
  channels: ['api', 'events']


services:

  monolog.processor.request:
    class: App\Shared\Infrastructure\Monolog\Processor\RequestProcessor
    arguments:
      - '@request_stack'
    tags:
      - { name: monolog.processor, handler: api_request }

  app.infrastructure.monolog.formatter.logstash:
    class: App\Shared\Infrastructure\Monolog\Formatter\LogstashFormatter
